version: '3.3'
services:
  postgres:
    image: postgres:16.4
    volumes:
      - ./local/postgres:/var/lib/postgresql/data
    restart: always
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U $POSTGRES_USER -d $POSTGRES_DB']
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s
    env_file:
      - ./.env.dev
    ports:
      - 5432:5432
    networks:
      - nestjs_network

networks:
  nestjs_network:
    driver: bridge
